services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    entrypoint: ["/entrypoint.sh", "backend"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    entrypoint: ["/entrypoint.sh", "celery-worker"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    entrypoint: ["/entrypoint.sh", "celery-beat"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6378:6379"

volumes:
  pgdata: